spring:
  jpa:
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/jwt-security
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
app:
  name: springboot-jwt-demo

jwt:
  header: Authorization
  expires_in: 300 # 5 minutes
  mobile_expires_in: 600 # 60 minutes
  secret: queenvictoria
  cookie: AUTH-TOKEN